#!/usr/bin/perl
use v5.10;
use warnings;
use strict;
use lib 'lib';
use Gtk2 -init;
use Forest::Gtk2;
use Forest::Tree;
use Forest::Tree::Reader::SimpleTextFile;

                


my $reader = Forest::Tree::Reader::SimpleTextFile->new;
$reader->read(\*DATA);



my $tree_view = Forest::Gtk2::tree_to_tree_view($reader->tree); 

my $window = Gtk2::Window->new('toplevel');
$window->add($tree_view);
$window->show_all;
Gtk2->main;


__DATA__
root
    1.0
        1.1
        1.2
            1.2.1
    2.0
        2.1
    3.0
    4.0
        4.1
            4.1.1
